### ISSUE TITLE
Create Java Badge

### ISSUE THREAD

**Issue by devandrets** [Aveek-Saha/GitHub-Profile-Badges#2]
Hello, there is no Java Badge, is it possible to create a Java Badge?

**Comment by Aveek-Saha** [comment]
Unfortunately this wont be possible since this project uses Simple Icons and as mentioned in their issue: https://github.com/simple-icons/simple-icons/issues/7374 the Java logo was removed for legal reasons. 

If the logo is ever added to Simple Icons this repo should update the changes automatically.
